/**
 * Common-password blocklist (roadmap M02 §Validation: "reject
 * 1000-most-common list"). Checked case-insensitively AFTER the
 * complexity rules, so the list concentrates on passwords that would
 * otherwise pass (Password1, Welcome123…) plus the classic top entries;
 * the base×suffix expansion reproduces the patterns that dominate real
 * leaked-password lists (>1000 entries total).
 */

const LITERALS = [
  '123456',
  '12345678',
  '123456789',
  '1234567890',
  'password',
  'qwerty',
  'qwerty123',
  'abc123',
  'iloveyou',
  '111111',
  '123123',
  'admin',
  'letmein',
  'welcome',
  'monkey',
  'dragon',
  'sunshine',
  'princess',
  'football',
  'baseball',
  'superman',
  'batman',
  'trustno1',
  'master',
  'shadow',
  'michael',
  'jennifer',
  'computer',
  'whatever',
  'freedom',
  'starwars',
  'passw0rd',
  'p@ssw0rd',
  'p@ssword',
  'pa$$word',
  'secret',
  'hello123',
  'charlie',
  'donald',
  'flower',
  'hottie',
  'loveme',
  'zaq12wsx',
  '1qaz2wsx',
  'qazwsx',
  'asdfgh',
  'zxcvbnm',
  'asdf1234',
  '1q2w3e4r',
  '1q2w3e4r5t',
  'q1w2e3r4',
  'qwertyuiop',
  'password!',
  'aa123456',
  'a1b2c3d4',
  'abcd1234',
  'admin123',
  'root123',
  'pass123',
  'test123',
  'user123',
  'demo123',
  'temp123',
  'login123',
  'access123',
  'bangladesh',
  'dhaka1234',
  'cricket123',
  'allah786',
  'bismillah',
];

const BASES = [
  'password',
  'welcome',
  'summer',
  'winter',
  'spring',
  'autumn',
  'monday',
  'sunday',
  'friday',
  'january',
  'february',
  'march',
  'april',
  'june',
  'july',
  'august',
  'october',
  'december',
  'qwerty',
  'dragon',
  'monkey',
  'shadow',
  'master',
  'letmein',
  'freedom',
  'sunshine',
  'princess',
  'flower',
  'butterfly',
  'football',
  'cricket',
  'baseball',
  'soccer',
  'hockey',
  'superman',
  'batman',
  'spiderman',
  'pokemon',
  'naruto',
  'michael',
  'jessica',
  'ashley',
  'daniel',
  'charlie',
  'thomas',
  'robert',
  'jordan',
  'harley',
  'ginger',
  'pepper',
  'cookie',
  'chocolate',
  'banana',
  'orange',
  'purple',
  'yellow',
  'silver',
  'golden',
  'diamond',
  'tigers',
  'eagles',
  'liverpool',
  'chelsea',
  'arsenal',
  'barcelona',
  'realmadrid',
  'ferrari',
  'porsche',
  'mustang',
  'toyota',
  'honda',
  'yamaha',
  'suzuki',
  'samsung',
  'google',
  'facebook',
  'internet',
  'computer',
  'laptop',
  'iphone',
  'android',
  'gamer',
  'ninja',
  'wizard',
  'knight',
  'angel',
  'devil',
  'heaven',
  'forever',
  'family',
  'mother',
  'father',
  'buddy',
  'lucky',
  'happy',
  'smile',
  'peace',
  'money',
  'dollar',
  'winner',
  'student',
  'teacher',
  'school',
  'college',
  'admin',
  'manager',
  'office',
  'dhaka',
  'bengal',
  'bangla',
  'shakib',
  'tamim',
];

const SUFFIXES = [
  '1',
  '12',
  '123',
  '1234',
  '12345',
  '!',
  '@',
  '#',
  '01',
  '2023',
  '2024',
  '2025',
  '2026',
  '69',
  '007',
  '786',
  '321',
  '111',
  '000',
];

const all = new Set<string>();
for (const literal of LITERALS) all.add(literal.toLowerCase());
for (const base of BASES) {
  all.add(base);
  for (const suffix of SUFFIXES) {
    // Stored lowercase; the case-insensitive check also catches
    // "Password123", "CRICKET786", etc.
    all.add(base + suffix);
  }
}

export const COMMON_PASSWORDS: ReadonlySet<string> = all;

export function isCommonPassword(password: string): boolean {
  return COMMON_PASSWORDS.has(password.toLowerCase());
}
