import { PERMISSION_REGISTRY } from './permission.registry';

/**
 * System role catalog (roadmap M03 §3): seeded per school, non-deletable,
 * non-renamable. `corePermissions` is each role's locked baseline — the
 * seeder grants them and PUT /roles/:id/permissions refuses to remove
 * them (extend-only). Defaults grow as later modules add codes: each
 * module extends these arrays and the idempotent seeder grants the new
 * codes on the next deploy (it never revokes admin-added extras).
 */

export interface SystemRoleDefinition {
  name: string;
  slug: string;
  description: string;
  /** Locked baseline permission codes (must exist in the registry). */
  corePermissions: string[];
}

const ALL_CODES = PERMISSION_REGISTRY.map((p) => p.code);

export const SYSTEM_ROLES: ReadonlyArray<SystemRoleDefinition> = [
  {
    name: 'Super Admin',
    slug: 'super-admin',
    description:
      'Full platform access. Bypasses permission checks entirely (guard-level, by user type and by this role).',
    corePermissions: [...ALL_CODES],
  },
  {
    name: 'Admin',
    slug: 'admin',
    description: 'School administrator — manages the whole school system.',
    corePermissions: [...ALL_CODES],
  },
  {
    name: 'Principal',
    slug: 'principal',
    description: 'Head of institution — oversight across academics and staff.',
    corePermissions: [
      'role.view',
      'permission.view',
      'user.role.view',
      'audit.view',
      'settings.view',
      'grading.view',
      'session.view',
      'session.activate',
      'calendar.view',
      'holiday.create',
      'holiday.update',
      'holiday.delete',
      'holiday.import',
      'event.create',
      'event.update',
      'event.delete',
      'structure.view',
      'department.manage',
      'shift.manage',
      'class.manage',
      'group.manage',
      'section.manage',
      'subject.manage',
      'class.subject.assign',
      'structure.clone',
      'staff.view',
      'staff.create',
      'staff.update',
      'staff.status',
      'staff.document.manage',
      'user.view',
      'teacher.view',
      'teacher.create',
      'teacher.update',
      'teacher.status',
      'teacher.qualification.manage',
      'teacher.document.manage',
      'teacher.subject.assign',
      'teacher.assign',
      'teacher.assign.override',
      'teacher.leave.manage',
      'teacher.leave.approve',
      'teacher.evaluation.manage',
      'student.view',
      'student.create',
      'student.update',
      'student.status',
      'student.medical.view',
      'student.medical.update',
      'student.document.manage',
      'student.guardian.manage',
      'student.account.create',
      'student.idcard.generate',
      'student.import',
      'guardian.view',
      'guardian.manage',
      'admission.view',
      'admission.cycle.manage',
      'admission.merit.generate',
      'admission.admit',
      'admission.payment.waive',
      'enrollment.view',
      'enrollment.create',
      'enrollment.update',
      'enrollment.delete',
      'enrollment.transfer',
      'enrollment.capacity.override',
      'enrollment.roll.assign',
      'promotion.view',
      'promotion.manage',
      'promotion.execute',
      'attendance.view',
      'attendance.mark',
      'attendance.edit',
      'attendance.edit.past',
      'attendance.holiday.override',
      'attendance.qr.checkin',
      'attendance.staff.view',
      'attendance.staff.mark',
      'attendance.report',
      'student.leave.view',
      'student.leave.manage',
      'student.leave.approve',
      'timetable.view',
      'period.slot.manage',
      'timetable.manage',
      'timetable.publish',
      'timetable.assign.override',
      'timetable.export',
      'exam.view',
      'exam.type.manage',
      'exam.manage',
      'exam.schedule',
      'exam.schedule.override',
      'exam.status',
      'exam.publish',
      'exam.seat-plan.manage',
      'exam.admit-card',
      'exam.admit-card.dues-override',
      'exam.export',
      'mark.view',
      'mark.entry',
      'mark.submit',
      'mark.verify',
      'mark.lock',
      'mark.correction',
      'result.view',
      'result.process',
      'result.process.override',
      'result.publish',
      'result.withhold',
      'result.combine',
      'result.export',
      // M16 — the Principal signs off waivers and refunds.
      'fee.view',
      'fee.setup',
      'fee.override.manage',
      'fee.override.approve',
      'fee.invoice.generate',
      'fee.invoice.cancel',
      'fee.collect',
      'fee.overpay',
      'fee.refund',
      'fee.report',
      'fee.export',
      // M17 — the Principal owns the school's voice: templates, notices,
      // bulk sends (including large blasts) and the SMS balance.
      'notification.view',
      'notification.template.manage',
      'notification.send',
      'notification.bulk',
      'notification.bulk.large',
      'notice.view',
      'notice.manage',
      'notice.publish',
      'sms.credit.view',
      'sms.credit.manage',
    ],
  },
  {
    name: 'Vice Principal',
    slug: 'vice-principal',
    description: 'Deputy head — academic oversight.',
    corePermissions: [
      'role.view',
      'user.role.view',
      'grading.view',
      'session.view',
      'calendar.view',
      'event.create',
      'event.update',
      'structure.view',
      'section.manage',
      'class.subject.assign',
      'staff.view',
      'user.view',
      'teacher.view',
      'teacher.assign',
      'teacher.leave.approve',
      'student.view',
      'student.status',
      'guardian.view',
      'enrollment.view',
      'enrollment.create',
      'enrollment.transfer',
      'enrollment.roll.assign',
      'promotion.view',
      'promotion.manage',
      'attendance.view',
      'attendance.mark',
      'attendance.edit',
      'attendance.staff.view',
      'attendance.report',
      'student.leave.view',
      'student.leave.approve',
      'timetable.view',
      'timetable.manage',
      'timetable.publish',
      'timetable.export',
      // Runs the exam cycle up to publication — the result announcement
      // itself stays with the Principal.
      'exam.view',
      'exam.manage',
      'exam.schedule',
      'exam.status',
      'exam.seat-plan.manage',
      'exam.admit-card',
      'exam.export',
      // Verifies and locks what the teachers entered, and runs the
      // processor — but publication stays with the Principal, as with
      // the exam status machine's final step.
      'mark.view',
      'mark.entry',
      'mark.submit',
      'mark.verify',
      'mark.lock',
      'result.view',
      'result.process',
      'result.export',
    ],
  },
  {
    name: 'Teacher',
    slug: 'teacher',
    description:
      'Teaching staff — colleague directory, own schedule, class attendance, the exam routine they invigilate, and mark entry for their own papers.',
    corePermissions: [
      'grading.view',
      'session.view',
      'calendar.view',
      'structure.view',
      'teacher.view',
      'student.view',
      'guardian.view',
      'enrollment.view',
      'attendance.view',
      'attendance.mark',
      'attendance.qr.checkin',
      'student.leave.view',
      // Own routine + the section grids they teach (read-only).
      'timetable.view',
      'timetable.export',
      // Read-only exam routine — invigilators need the sitting schedule
      // and seat plans.
      'exam.view',
      'exam.export',
      // Enters and submits marks; verifying and locking are somebody
      // else's job by design, which is the point of a four-eyes flow.
      'mark.view',
      'mark.entry',
      'mark.submit',
      'result.view',
    ],
  },
  {
    name: 'Accountant',
    slug: 'accountant',
    description:
      'Fees and finance — fee setup, invoicing, the collection desk and the money reports (Module 16). Accounting vouchers arrive with Module 20.',
    corePermissions: [
      'session.view',
      'structure.view',
      'student.view',
      'guardian.view',
      'enrollment.view',
      'fee.view',
      'fee.setup',
      'fee.override.manage',
      'fee.invoice.generate',
      'fee.invoice.cancel',
      'fee.collect',
      'fee.refund',
      'fee.report',
      'fee.export',
      // Deliberately NOT granted: `fee.override.approve` (a waiver needs
      // a senior's sign-off) and `fee.overpay` — the two places where
      // taking the money and authorising it must be different people.
    ],
  },
  {
    name: 'Admission Officer',
    slug: 'admission-officer',
    description:
      'Admissions desk — student registration and the full application pipeline (Module 10).',
    corePermissions: [
      'structure.view',
      'session.view',
      'student.view',
      'student.create',
      'student.update',
      'student.document.manage',
      'student.guardian.manage',
      'student.idcard.generate',
      'student.import',
      'guardian.view',
      'guardian.manage',
      'admission.view',
      'admission.cycle.manage',
      'admission.application.review',
      'admission.payment.record',
      'admission.test.manage',
      'admission.merit.generate',
      'admission.admit',
      'enrollment.view',
      'enrollment.create',
      'enrollment.roll.assign',
    ],
  },
  {
    name: 'Librarian',
    slug: 'librarian',
    description: 'Library desk. Permissions arrive with Module 23.',
    corePermissions: [],
  },
  {
    name: 'Student',
    slug: 'student',
    description: 'Student portal access (ownership-scoped).',
    corePermissions: [],
  },
  {
    name: 'Parent',
    slug: 'parent',
    description: 'Parent/guardian portal access (children-scoped).',
    corePermissions: [],
  },
  {
    name: 'Office Staff',
    slug: 'office-staff',
    description:
      'General office staff — directory access, the notice board and day-to-day messaging.',
    corePermissions: [
      'staff.view',
      // M17 — the office desk writes notices and runs routine sends.
      'notification.view',
      'notification.send',
      'notification.bulk',
      'notice.view',
      'notice.manage',
      'notice.publish',
      'sms.credit.view',
    ],
  },
];

export const SYSTEM_ROLE_SLUGS: ReadonlySet<string> = new Set(
  SYSTEM_ROLES.map((r) => r.slug),
);

/** Locked baseline per system-role slug (empty set for unknown slugs). */
export function coreLockedPermissions(slug: string): ReadonlySet<string> {
  const def = SYSTEM_ROLES.find((r) => r.slug === slug);
  return new Set(def?.corePermissions ?? []);
}
